
package my.screen;

import database.Cities;
import database.Weather;
import java.awt.Color;
import java.awt.Image;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import weatherapp.WebHandler;
import javax.swing.Timer;

/**
 *
 * @author oikon
 */
public class screen extends javax.swing.JFrame {

    private Weather weather;
    private Cities city;
    private WebHandler wh;
    /**
     * Creates new form screen
     */
    public screen() {
        wh = new WebHandler();
        city = new Cities();
        weather = new Weather();
        initComponents();
        setBackgroundImage();
    }
    
  
    private void setBackgroundImage() {
    String localDir = System.getProperty("user.dir");
    
    String imagePath = localDir+"\\sky.png"; //background image
    ImageIcon backgroundImage = new ImageIcon(imagePath);
    Image image = backgroundImage.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);//fit στο παράθυρο
    backgroundImage = new ImageIcon(image);
    JLabel backgroundLabel = new JLabel(backgroundImage);
    backgroundLabel.setBounds(0, 0, getWidth(), getHeight()); 

    // adds the background image to the contentPane of the window
    ((JPanel) getContentPane()).setOpaque(false);
    getLayeredPane().add(backgroundLabel, Integer.valueOf(Integer.MIN_VALUE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTextField_input = new javax.swing.JTextField();
        jButton_exit = new javax.swing.JButton();
        jButton_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_istoriko = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to our WeαtherApp");

        jTextField_input.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jTextField_input.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_input.setText("Αναζήτηση πόλης: ");
        jTextField_input.setAutoscrolls(false);
        jTextField_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_inputFocusLost(evt);
            }
        });

        jButton_exit.setText("Έξοδος");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jButton_submit.setText("Submit");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        jLabel1.setText("Παρακαλώ εισάγετε το όνομα της πόλης.");

        jButton_istoriko.setText("Ιστορικό αναζητήσεων");
        jButton_istoriko.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_istoriko.setFocusPainted(false);
        jButton_istoriko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_istorikoActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_input, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jButton_submit)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton_istoriko, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_istoriko, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButton_exit)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_inputFocusGained
        if (jTextField_input.getText().equals("Αναζήτηση πόλης: ")){
            jTextField_input.setText("");
            jTextField_input.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField_inputFocusGained

    private void jTextField_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_inputFocusLost
        //When the user clicks elsewhere
        if (jTextField_input.getText().equals("")){
            jTextField_input.setText("Αναζήτηση πόλης: ");
            jTextField_input.setForeground(new Color(155,155,155));
        }
    }//GEN-LAST:event_jTextField_inputFocusLost
    
    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
       int choice = JOptionPane.showConfirmDialog(null, "Είστε σίγουρος ότι θέλετε να κλείσετε το πρόγραμμα;", "Έξοδος", JOptionPane.YES_NO_OPTION);
        
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0); // Κλείσιμο του προγράμματος(οχι μονο της οθονης)
        }
    }//GEN-LAST:event_jButton_exitActionPerformed

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        String cityinp = jTextField_input.getText().trim(); //takes the name of the city and remove the spaces from the beginning and the end
    
        if (!isValidCityName(cityinp)) {
            timedMessage("Μη έγκυρο όνομα πόλης");
            return;
        }
        String msg = null;

        try {
            if (wh.getCityAndWeather(cityinp, city, weather)) {
                // jumps to second screen, it displays the weather data for the selected city
                SecondScreen mySecondScreen = new SecondScreen(this.city,this.weather);
                mySecondScreen.setVisible(true);
                dispose();
            }else{
                timedMessage(wh.getMsg());
            }
        } catch (ParseException ex) {
            Logger.getLogger(screen.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    //  Validation of city name
    private boolean isValidCityName(String cityName) {
        return cityName != null && !cityName.isEmpty() && !containsSpecialCharacters(cityName);
    }
    // Checking if the text contains special characters
    private boolean containsSpecialCharacters(String str) {
        return !str.matches("[a-zA-Z0-9\u0370-\u03FF ]*");
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jButton_istorikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_istorikoActionPerformed
        // TODO add your handling code here:
       thirdScreen mythirdscreen = new thirdScreen();
       mythirdscreen.setVisible(true); //jumps to thirdscreen
       dispose();
    }//GEN-LAST:event_jButton_istorikoActionPerformed

    private void timedMessage(String str){
        Timer timer = new Timer(2000, e -> { 
        //timer (2sec) for the wrong input message
        // reset of the message when the timer is disabled
        jLabel1.setText("Παρακαλώ εισάγετε το όνομα της πόλης.");
        });
        timer.setRepeats(false); // executed only once
        jLabel1.setText(str);
        timer.start();
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_istoriko;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextField_input;
    // End of variables declaration//GEN-END:variables
}
